/**
 * The Key column of the API credentials table.
 *
 * The thing a reviewer would notice being wrong here is the show button
 * appearing on a row that can never produce a value. A Vocion token issued
 * before minted tokens were stored encrypted holds a hash and nothing else, so
 * its row has to explain itself and offer a way forward instead of a button
 * that fails on click.
 */
import { describe, expect, it, vi } from 'vitest';
import { render } from 'vitest-browser-react';
import { page, userEvent } from 'vitest/browser';

const list = vi.fn();
const listPlatforms = vi.fn();
const revealPlatformKey = vi.fn();

vi.mock('@/libs/Orpc', () => ({
  client: {
    apiTokens: {
      list: () => list(),
      listPlatforms: () => listPlatforms(),
      revealPlatformKey: (input: { tokenId: string }) => revealPlatformKey(input),
      create: vi.fn(),
      createPlatformKey: vi.fn(),
      revoke: vi.fn(),
    },
  },
}));

const { ApiTokensPanel } = await import('./ApiTokensPanel');

const VOCION_PLATFORM = {
  id: 'vocion',
  label: 'Vocion',
  keySource: 'minted' as const,
  keyShapeHint: 'generated by Vocion',
  helpText: 'A token an outside tool presents to the Vocion API.',
  fields: [],
};

const TOKEN = 'vcn_live_abc123_deadbeefdeadbeef';

/**
 * One row of the credential table, as `apiTokens.list` returns it.
 * @param overrides - The fields this particular row is about.
 */
function tokenRow(overrides: Record<string, unknown>) {
  return {
    id: 'tok-1',
    name: 'FirstHQ',
    platform: 'vocion',
    createdAt: new Date('2026-09-01'),
    lastUsedAt: null,
    revokedAt: null,
    expiresAt: null,
    keyHint: '…beef',
    revealable: true,
    ...overrides,
  };
}

/**
 * Render the panel with one credential row and wait for its first load.
 * @param row - The row `apiTokens.list` should answer with.
 */
async function renderWithRow(row: Record<string, unknown>) {
  list.mockResolvedValue([row]);
  listPlatforms.mockResolvedValue([VOCION_PLATFORM]);
  render(<ApiTokensPanel />);

  await expect.element(page.getByText('FirstHQ')).toBeVisible();
}

describe('the Key column', () => {
  it('offers a show button for a Vocion token that can be decrypted', async () => {
    await renderWithRow(tokenRow({ revealable: true }));

    await expect.element(page.getByLabelText('Show key')).toBeVisible();
  });

  it('shows the token and a copy button once the admin asks for it', async () => {
    revealPlatformKey.mockResolvedValue({ status: 'ok', values: { token: TOKEN } });
    await renderWithRow(tokenRow({ revealable: true }));

    await userEvent.click(page.getByLabelText('Show key'));

    await expect.element(page.getByText(TOKEN)).toBeVisible();
    await expect.element(page.getByLabelText('Copy key')).toBeVisible();
  });

  it('puts the token away again when the admin hides it', async () => {
    revealPlatformKey.mockResolvedValue({ status: 'ok', values: { token: TOKEN } });
    await renderWithRow(tokenRow({ revealable: true }));

    await userEvent.click(page.getByLabelText('Show key'));

    await expect.element(page.getByText(TOKEN)).toBeVisible();

    await userEvent.click(page.getByLabelText('Hide key'));

    await expect.element(page.getByText(TOKEN)).not.toBeInTheDocument();
  });

  it('says why a reveal failed instead of leaving the row silent', async () => {
    revealPlatformKey.mockRejectedValue(new Error('boom'));
    await renderWithRow(tokenRow({ revealable: true }));

    await userEvent.click(page.getByLabelText('Show key'));

    await expect.element(page.getByText('Could not read that key.')).toBeVisible();
  });

  it('offers no show button for a token issued before tokens were kept encrypted', async () => {
    await renderWithRow(tokenRow({ revealable: false }));

    expect(page.getByLabelText('Show key').elements()).toHaveLength(0);
  });

  it('tells the admin how to get a token they can read back', async () => {
    await renderWithRow(tokenRow({ revealable: false }));

    // The way forward has to be readable rather than parked in a tooltip: this
    // row is otherwise a dead end for anyone who lost the original.
    await expect
      .element(page.getByText('Revoke it and create a new one to get a token you can show again.'))
      .toBeVisible();
  });
});
