/**
 * Credential platform registry — the list of platforms an org can hold a
 * credential for, and the rules for each one.
 *
 * Two very different things live in the same `api_token` table, and this
 * registry is what tells them apart:
 *
 *   - **Minted** (`vocion`). Vocion generates the secret, stores only its
 *     SHA-256, and shows the plaintext once. This is the credential an outside
 *     caller presents *to* Vocion.
 *   - **Supplied** (`openai`, `anthropic`, …). The person pastes the platform's
 *     own key. Vocion encrypts it at rest and later decrypts it to call *out*
 *     to that platform on the org's behalf, so the org's own account is billed.
 *
 * Adding a platform means adding a descriptor here. Nothing else in the
 * service, router or UI enumerates platforms.
 */

import type { LLMProviderName } from '@vocion/sdk';

/** Every platform id this build understands. */
export type CredentialPlatformId
  = | 'vocion'
    | 'openai'
    | 'anthropic'
    | 'vertex'
    | 'azure-openai'
    | 'aws'
    | 'custom';

/**
 * Where a platform's secret comes from.
 *
 * `minted` — Vocion generates it. `supplied` — the person pastes the
 * platform's own key.
 */
export type KeySource = 'minted' | 'supplied';

/**
 * One input a platform's credential is made of.
 *
 * Most platforms need a single secret string. AWS needs a pair — an access key
 * id, which is an identifier rather than a secret, and a secret access key
 * which very much is. Modelling fields explicitly is what lets the form and the
 * masking do the right thing for both.
 */
export type CredentialField = {
  /** Key this value is stored under inside the encrypted document. */
  name: string;
  /** Label on the form field. */
  label: string;
  /** Shape this value must match, or null to accept any non-empty string. */
  pattern: RegExp | null;
  /** Plain-language description of the expected shape, used in error text. */
  shapeHint: string;
  /**
   * Whether this value is secret. A non-secret field (an AWS access key id) is
   * shown back in full; a secret one is never readable again after saving.
   */
  secret: boolean;
};

export type CredentialPlatform = {
  id: CredentialPlatformId;
  /** Name shown in the platform selector. */
  label: string;
  keySource: KeySource;
  /**
   * The LLM provider this platform's key authenticates, or `null` when the
   * platform is not an LLM provider at all (`vocion`, `custom`). Outbound
   * model calls resolve their key by looking up the platform whose
   * `llmProvider` matches the provider they are about to use.
   */
  llmProvider: LLMProviderName | null;
  /**
   * Shape a pasted key must match. `null` means any non-empty string is
   * accepted — the right answer for `custom`, and for platforms whose
   * credential format we do not want to guess at.
   */
  keyPattern: RegExp | null;
  /** Plain-language description of the expected shape, used in error text. */
  keyShapeHint: string;
  /** One line of guidance shown under the paste field. */
  helpText: string;
  /**
   * The inputs this credential is made of, in form order. Single-secret
   * platforms have exactly one; AWS has two.
   */
  fields: readonly CredentialField[];
};

/**
 * The single-secret field shape almost every platform uses.
 * @param label
 * @param pattern
 * @param shapeHint
 */
function singleKeyField(label: string, pattern: RegExp | null, shapeHint: string): readonly CredentialField[] {
  return [{ name: 'apiKey', label, pattern, shapeHint, secret: true }];
}

/**
 * The platform table. `vocion` is first because it is the default selection
 * and the only minted entry.
 */
const PLATFORMS: readonly CredentialPlatform[] = [
  {
    id: 'vocion',
    label: 'Vocion',
    keySource: 'minted',
    llmProvider: null,
    keyPattern: null,
    keyShapeHint: 'generated by Vocion',
    helpText: 'A token an outside tool presents to the Vocion API. Shown once, at creation.',
    fields: [],
  },
  {
    id: 'openai',
    label: 'OpenAI',
    keySource: 'supplied',
    llmProvider: 'openai',
    // OpenAI keys begin `sk-` and carry a long opaque tail. Project and
    // service-account keys (`sk-proj-…`, `sk-svcacct-…`) match the same shape.
    keyPattern: /^sk-[\w-]{16,}$/i,
    keyShapeHint: 'starts with "sk-" followed by at least 16 more characters',
    helpText: 'Your OpenAI secret key. Model calls for this workspace bill your OpenAI account.',
    fields: singleKeyField('OpenAI key', /^sk-[\w-]{16,}$/i, 'starts with "sk-" followed by at least 16 more characters'),
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    keySource: 'supplied',
    llmProvider: 'anthropic',
    keyPattern: /^sk-ant-[\w-]{16,}$/i,
    keyShapeHint: 'starts with "sk-ant-" followed by at least 16 more characters',
    helpText: 'Your Anthropic API key. Model calls for this workspace bill your Anthropic account.',
    fields: singleKeyField('Anthropic key', /^sk-ant-[\w-]{16,}$/i, 'starts with "sk-ant-" followed by at least 16 more characters'),
  },
  {
    id: 'vertex',
    label: 'Google Vertex AI',
    keySource: 'supplied',
    // A Vertex credential is a service-account JSON document or a short-lived
    // access token depending on how the customer authenticates, so there is no
    // single shape worth enforcing.
    llmProvider: 'vertex',
    keyPattern: null,
    keyShapeHint: 'any non-empty credential',
    helpText: 'A Vertex AI access token or the contents of a service-account JSON key.',
    fields: singleKeyField('Vertex credential', null, 'any non-empty credential'),
  },
  {
    id: 'azure-openai',
    label: 'Azure OpenAI',
    keySource: 'supplied',
    llmProvider: 'azure-openai',
    // Azure resource keys are 32+ hex-ish characters with no prefix.
    keyPattern: /^[A-Z0-9]{32,}$/i,
    keyShapeHint: 'at least 32 letters and digits, with no prefix',
    helpText: 'The key from your Azure OpenAI resource, under Keys and Endpoint.',
    fields: singleKeyField('Azure OpenAI key', /^[A-Z0-9]{32,}$/i, 'at least 32 letters and digits, with no prefix'),
  },
  {
    id: 'aws',
    label: 'AWS',
    keySource: 'supplied',
    // Not an LLM provider in its own right — Bedrock is reached through the
    // AWS SDK, not through the `LLMProviderName` adapters — so nothing in the
    // model path picks this up implicitly. That is deliberate; see
    // `resolveAwsCredentials` for why AWS does not get the automatic env
    // fallback the model providers get.
    llmProvider: null,
    keyPattern: null,
    keyShapeHint: 'an access key id (starting AKIA or ASIA) plus its secret access key',
    helpText: 'An IAM access key pair for this workspace. Scope it to only what you want Vocion to reach.',
    fields: [
      {
        name: 'accessKeyId',
        label: 'Access key ID',
        // AKIA = long-lived IAM user key, ASIA = temporary STS key.
        pattern: /^(?:AKIA|ASIA)[A-Z0-9]{12,}$/,
        shapeHint: 'starts with AKIA or ASIA followed by at least 12 more characters',
        // An access key id is an identifier, not a secret — AWS puts it in
        // request headers in the clear. Showing it back is what makes the
        // stored pair identifiable in the UI.
        secret: false,
      },
      {
        name: 'secretAccessKey',
        label: 'Secret access key',
        pattern: /^[A-Z0-9/+=]{40,}$/i,
        shapeHint: 'is at least 40 characters',
        secret: true,
      },
    ],
  },
  {
    id: 'custom',
    label: 'Other platform',
    keySource: 'supplied',
    llmProvider: null,
    keyPattern: null,
    keyShapeHint: 'any non-empty credential',
    helpText: 'Any other credential you want this workspace to keep. Stored encrypted; nothing calls it automatically.',
    fields: singleKeyField('Credential', null, 'any non-empty credential'),
  },
];

/** How many trailing characters of a supplied key the UI is allowed to show. */
const KEY_HINT_CHARS = 4;

/** The platform every row falls back to — the historical behaviour of this table. */
export const DEFAULT_PLATFORM_ID: CredentialPlatformId = 'vocion';

/** Every platform, in the order the selector should list them. */
export function listPlatforms(): readonly CredentialPlatform[] {
  return PLATFORMS;
}

/**
 * Whether `value` names a platform this build knows.
 * @param value - Candidate platform id, typically off the wire.
 */
export function isCredentialPlatformId(value: unknown): value is CredentialPlatformId {
  return typeof value === 'string' && PLATFORMS.some(platform => platform.id === value);
}

/**
 * Look up a platform descriptor. Throws on an unknown id rather than returning
 * undefined: every caller here treats an unknown platform as a bug or a
 * tampered request, never as a case to handle.
 * @param id - The platform id to resolve.
 */
export function getPlatform(id: CredentialPlatformId): CredentialPlatform {
  const platform = PLATFORMS.find(candidate => candidate.id === id);
  if (!platform) {
    throw new Error(`unknown credential platform: ${id}`);
  }
  return platform;
}

/**
 * The platform whose stored key authenticates `provider`, or `null` when no
 * platform maps to it. This is the bridge from "the model call needs an
 * Anthropic key" back to "look for the org's `anthropic` row".
 * @param provider - The LLM provider about to be called.
 */
export function platformForLLMProvider(provider: LLMProviderName): CredentialPlatform | null {
  return PLATFORMS.find(platform => platform.llmProvider === provider) ?? null;
}

/**
 * Validate a pasted key against its platform and return it trimmed.
 *
 * Throws a message written for the person pasting the key. The message names
 * the expected shape but never echoes the value — an error string is one of
 * the easiest places for a secret to leak into a log.
 * @param id - The platform the key belongs to.
 * @param rawKey - The key exactly as the person supplied it.
 */
export function validatePlatformKey(id: CredentialPlatformId, rawKey: string): string {
  const platform = getPlatform(id);
  const [field] = platform.fields;
  if (platform.keySource === 'supplied' && platform.fields.length > 1) {
    throw new Error(`${platform.label} needs more than one value; use validatePlatformCredential.`);
  }
  const values = validatePlatformCredential(id, { [field?.name ?? 'apiKey']: rawKey });
  return values[field!.name]!;
}

/** A credential's values, keyed by field name. */
export type CredentialValues = Record<string, string>;

/**
 * Validate every field of a supplied credential and return the trimmed values.
 *
 * Throws a message written for the person filling the form. The message names
 * the field and the expected shape but never echoes a value — an error string
 * is one of the easiest places for a secret to leak into a log.
 * @param id - The platform the credential belongs to.
 * @param rawValues - Field values exactly as the person supplied them.
 */
export function validatePlatformCredential(
  id: CredentialPlatformId,
  rawValues: CredentialValues,
): CredentialValues {
  const platform = getPlatform(id);
  if (platform.keySource === 'minted') {
    throw new Error(`${platform.label} keys are generated by Vocion, not supplied.`);
  }
  const values: CredentialValues = {};
  for (const field of platform.fields) {
    const value = (rawValues[field.name] ?? '').trim();
    if (value.length === 0) {
      throw new Error(`Enter the ${field.label}.`);
    }
    if (field.pattern && !field.pattern.test(value)) {
      throw new Error(`That does not look like a valid ${field.label} — it ${field.shapeHint}.`);
    }
    values[field.name] = value;
  }
  return values;
}

/**
 * The field whose value the list view should hint at — the last secret one, so
 * a pair like AWS hints at the secret access key rather than the access key id
 * that is already shown in full.
 * @param platform - The platform whose credential was stored.
 */
export function hintField(platform: CredentialPlatform): CredentialField | undefined {
  const secrets = platform.fields.filter(field => field.secret);
  return secrets[secrets.length - 1];
}

/**
 * The masked tail shown in the credential list, e.g. `…4a9F`. A key shorter
 * than the hint length is masked entirely rather than shown in full.
 * @param key - The plaintext key being stored.
 */
export function keyHint(key: string): string {
  if (key.length <= KEY_HINT_CHARS) {
    return '…';
  }
  return `…${key.slice(-KEY_HINT_CHARS)}`;
}
