/**
 * Supplied third-party keys in `api_token`, against PGlite.
 *
 * The two shapes now sharing this table pull in opposite directions, so these
 * tests pin the boundary between them: a supplied key must round-trip through
 * the vault, must be the only live key its platform holds, must disappear the
 * moment it is revoked or expires — and must never be usable as a Vocion
 * credential, no matter how it is presented.
 */
import process from 'node:process';
import { eq } from 'drizzle-orm';
import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('@/libs/DB');

const { db } = await import('@/libs/DB');
const { apiTokenSchema, sourceDekSchema } = await import('@/models/Schema');
const {
  issueToken,
  resolveAwsCredentials,
  resolvePlatformCredential,
  verifyToken,
  listTokens,
  revokeToken,
  storePlatformKey,
  resolvePlatformKey,
  revealPlatformCredential,
} = await import('@/services/ApiTokenService');

const ORG = 'org_platform_keys';
const OTHER_ORG = 'org_platform_keys_other';

const OPENAI_KEY = 'sk-abcdefghijklmnop1234';
const ANTHROPIC_KEY = 'sk-ant-abcdefghijklmnop1234';

async function clearCredentials(): Promise<void> {
  // api_token references source_dek, so credentials go first.
  await db.delete(apiTokenSchema);
  await db.delete(sourceDekSchema);
}

beforeEach(clearCredentials);

afterAll(clearCredentials);

describe('storePlatformKey', () => {
  it('round-trips a supplied key through the vault', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme OpenAI', platform: 'openai', apiKey: OPENAI_KEY });

    expect(await resolvePlatformKey(ORG, 'openai')).toBe(OPENAI_KEY);
  });

  it('returns a masked hint and never the key', async () => {
    const stored = await storePlatformKey({ orgId: ORG, name: 'Acme OpenAI', platform: 'openai', apiKey: OPENAI_KEY });

    expect(stored.keyHint).toBe('…1234');
    expect(JSON.stringify(stored)).not.toContain(OPENAI_KEY);
  });

  it('never writes the plaintext to the row', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme OpenAI', platform: 'openai', apiKey: OPENAI_KEY });
    const [row] = await db.select().from(apiTokenSchema);

    expect(JSON.stringify(row)).not.toContain(OPENAI_KEY);
    expect(row!.secretHash).toBeNull();
    expect(row!.ciphertext).toBeTruthy();
    expect(row!.dekId).not.toBeNull();
  });

  it('trims whitespace off a pasted key before storing it', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme', platform: 'openai', apiKey: `  ${OPENAI_KEY}\n` });

    expect(await resolvePlatformKey(ORG, 'openai')).toBe(OPENAI_KEY);
  });

  it('rejects a malformed key without storing anything', async () => {
    await expect(
      storePlatformKey({ orgId: ORG, name: 'Acme', platform: 'openai', apiKey: 'nonsense' }),
    ).rejects.toThrow(/does not look like a valid OpenAI key/);

    expect(await db.select().from(apiTokenSchema)).toHaveLength(0);
  });

  it('refuses to store a supplied key against the minted vocion platform', async () => {
    await expect(
      storePlatformKey({ orgId: ORG, name: 'Sneaky', platform: 'vocion', apiKey: 'anything' }),
    ).rejects.toThrow(/generated by Vocion/);
  });

  it('keeps one live key per platform, revoking the one it replaces', async () => {
    const first = await storePlatformKey({ orgId: ORG, name: 'Old', platform: 'openai', apiKey: OPENAI_KEY });
    const replacement = 'sk-zzzzzzzzzzzzzzzz9999';
    const second = await storePlatformKey({ orgId: ORG, name: 'New', platform: 'openai', apiKey: replacement });

    expect(await resolvePlatformKey(ORG, 'openai')).toBe(replacement);

    const rows = await listTokens(ORG);
    const oldRow = rows.find(row => row.id === first.id);
    const newRow = rows.find(row => row.id === second.id);

    // The replaced key is revoked, not deleted — the org can still see it held one.
    expect(oldRow?.revokedAt).not.toBeNull();
    expect(newRow?.revokedAt).toBeNull();
  });

  it('holds a separate live key for each platform', async () => {
    await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });
    await storePlatformKey({ orgId: ORG, name: 'ant', platform: 'anthropic', apiKey: ANTHROPIC_KEY });

    expect(await resolvePlatformKey(ORG, 'openai')).toBe(OPENAI_KEY);
    expect(await resolvePlatformKey(ORG, 'anthropic')).toBe(ANTHROPIC_KEY);
  });

  it('keeps one org from reading another org key', async () => {
    await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });

    expect(await resolvePlatformKey(OTHER_ORG, 'openai')).toBeNull();
  });
});

describe('resolvePlatformKey', () => {
  it('returns null when the org has stored nothing', async () => {
    expect(await resolvePlatformKey(ORG, 'anthropic')).toBeNull();
  });

  it('returns null once the key is revoked', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });
    await revokeToken(ORG, id);

    expect(await resolvePlatformKey(ORG, 'openai')).toBeNull();
  });

  it('returns null once the key has expired', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });
    await db
      .update(apiTokenSchema)
      .set({ expiresAt: new Date(Date.now() - 1000) })
      .where(eq(apiTokenSchema.id, id));

    expect(await resolvePlatformKey(ORG, 'openai')).toBeNull();
  });

  it('still returns a key whose expiry is in the future', async () => {
    await storePlatformKey({
      orgId: ORG,
      name: 'oai',
      platform: 'openai',
      apiKey: OPENAI_KEY,
      expiresAt: new Date(Date.now() + 60_000),
    });

    expect(await resolvePlatformKey(ORG, 'openai')).toBe(OPENAI_KEY);
  });

  it('returns null for the minted platform, which has nothing to decrypt', async () => {
    await issueToken({ orgId: ORG, name: 'a vocion token' });

    expect(await resolvePlatformKey(ORG, 'vocion')).toBeNull();
  });
});

describe('the two credential shapes never cross', () => {
  it('refuses a stored platform key presented as a Vocion bearer token', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });

    // Every way the row could be dressed up as a Vocion credential.
    expect(await verifyToken(OPENAI_KEY)).toBeNull();
    expect(await verifyToken(`vcn_live_${id}_${OPENAI_KEY}`)).toBeNull();
  });

  it('will not let a live Vocion token be rewritten into a platform row at all', async () => {
    const { token, id } = await issueToken({ orgId: ORG, name: 'legit' });

    expect(await verifyToken(token)).not.toBeNull();

    // Re-badging a minted token as a platform credential is the write that
    // would blur the two shapes. The CHECK constraint refuses it outright, so
    // `verifyToken`'s own platform guard is a second line rather than the only
    // one — and the token is left untouched and still working.
    await expect(
      db.update(apiTokenSchema)
        .set({ platform: 'custom', secretHash: null })
        .where(eq(apiTokenSchema.id, id)),
    ).rejects.toThrow(); // api_token_shape_ck; drizzle wraps the constraint name in `cause`.

    expect(await verifyToken(token)).not.toBeNull();
  });

  it('lets a Vocion token keep working alongside stored platform keys', async () => {
    const { token } = await issueToken({ orgId: ORG, name: 'legit' });
    await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });

    expect((await verifyToken(token))?.orgId).toBe(ORG);
  });

  it('allows many live Vocion tokens, unlike platform keys', async () => {
    await issueToken({ orgId: ORG, name: 'one' });
    await issueToken({ orgId: ORG, name: 'two' });

    const live = (await listTokens(ORG)).filter(row => row.revokedAt === null);

    expect(live).toHaveLength(2);
  });
});

describe('revealPlatformCredential', () => {
  it('returns the decrypted key for a live supplied credential', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });

    expect(await revealPlatformCredential(ORG, id)).toEqual({
      status: 'ok',
      values: { apiKey: OPENAI_KEY },
    });
  });

  it('returns every field of a multi-field credential', async () => {
    const pair = {
      accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
      secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    };
    const { id } = await storePlatformKey({ orgId: ORG, name: 'Acme AWS', platform: 'aws', values: pair });

    expect(await revealPlatformCredential(ORG, id)).toEqual({ status: 'ok', values: pair });
  });

  it('refuses a Vocion token, whose plaintext was never stored', async () => {
    const { id } = await issueToken({ orgId: ORG, name: 'a vocion token' });

    expect(await revealPlatformCredential(ORG, id)).toEqual({ status: 'minted' });
  });

  it('still opens a revoked key, which the vendor has not forgotten', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });
    await revokeToken(ORG, id);

    // Revoking stops Vocion using the key. Whoever has to go and delete it at
    // OpenAI still needs to be able to read it.
    expect(await revealPlatformCredential(ORG, id)).toEqual({
      status: 'ok',
      values: { apiKey: OPENAI_KEY },
    });
  });

  it('still opens an expired key', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });
    await db
      .update(apiTokenSchema)
      .set({ expiresAt: new Date(Date.now() - 1000) })
      .where(eq(apiTokenSchema.id, id));

    expect(await revealPlatformCredential(ORG, id)).toEqual({
      status: 'ok',
      values: { apiKey: OPENAI_KEY },
    });
  });

  it('still opens a key whose expiry is in the future', async () => {
    const { id } = await storePlatformKey({
      orgId: ORG,
      name: 'oai',
      platform: 'openai',
      apiKey: OPENAI_KEY,
      expiresAt: new Date(Date.now() + 60_000),
    });

    expect(await revealPlatformCredential(ORG, id)).toEqual({
      status: 'ok',
      values: { apiKey: OPENAI_KEY },
    });
  });

  it('reports an unknown id as not found', async () => {
    expect(await revealPlatformCredential(ORG, 'no-such-credential')).toEqual({ status: 'not-found' });
  });

  it('will not open another org’s key, even with the right id', async () => {
    const { id } = await storePlatformKey({ orgId: ORG, name: 'oai', platform: 'openai', apiKey: OPENAI_KEY });

    expect(await revealPlatformCredential(OTHER_ORG, id)).toEqual({ status: 'not-found' });
  });
});

describe('AWS credentials', () => {
  const AWS_PAIR = {
    accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
    secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
  };
  const originalId = process.env.AWS_ACCESS_KEY_ID;
  const originalSecret = process.env.AWS_SECRET_ACCESS_KEY;

  afterEach(() => {
    const restore = (key: string, value: string | undefined): void => {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    };
    restore('AWS_ACCESS_KEY_ID', originalId);
    restore('AWS_SECRET_ACCESS_KEY', originalSecret);
  });

  it('round-trips both halves of the pair', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme AWS', platform: 'aws', values: AWS_PAIR });

    expect(await resolveAwsCredentials(ORG)).toEqual(AWS_PAIR);
  });

  it('hints at the secret access key, not the access key id', async () => {
    const stored = await storePlatformKey({ orgId: ORG, name: 'Acme AWS', platform: 'aws', values: AWS_PAIR });

    expect(stored.keyHint).toBe('…EKEY');
  });

  it('never writes either half in the clear', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme AWS', platform: 'aws', values: AWS_PAIR });
    const [row] = await db.select().from(apiTokenSchema);

    expect(JSON.stringify(row)).not.toContain(AWS_PAIR.secretAccessKey);
    expect(JSON.stringify(row)).not.toContain(AWS_PAIR.accessKeyId);
  });

  it('does NOT fall back to the process AWS credentials by default', async () => {
    process.env.AWS_ACCESS_KEY_ID = 'AKIAPLATFORMACCOUNT1';
    process.env.AWS_SECRET_ACCESS_KEY = 'platform-account-secret-key-value-here12';

    // The platform's own AWS identity holds the KMS key wrapping every
    // tenant's DEK. Handing it to a tenant-scoped call by accident is a
    // privilege escalation, so the fallback is opt-in and this is the guard.
    expect(await resolveAwsCredentials(ORG)).toBeNull();
  });

  it('falls back only when the caller asks for it explicitly', async () => {
    process.env.AWS_ACCESS_KEY_ID = 'AKIAPLATFORMACCOUNT1';
    process.env.AWS_SECRET_ACCESS_KEY = 'platform-account-secret-key-value-here12';

    expect(await resolveAwsCredentials(ORG, { allowServerFallback: true })).toEqual({
      accessKeyId: 'AKIAPLATFORMACCOUNT1',
      secretAccessKey: 'platform-account-secret-key-value-here12',
    });
  });

  it('prefers the org own pair over the process credentials even when fallback is allowed', async () => {
    process.env.AWS_ACCESS_KEY_ID = 'AKIAPLATFORMACCOUNT1';
    process.env.AWS_SECRET_ACCESS_KEY = 'platform-account-secret-key-value-here12';
    await storePlatformKey({ orgId: ORG, name: 'Acme AWS', platform: 'aws', values: AWS_PAIR });

    expect(await resolveAwsCredentials(ORG, { allowServerFallback: true })).toEqual(AWS_PAIR);
  });

  it('returns null with fallback allowed but nothing in the environment', async () => {
    delete process.env.AWS_ACCESS_KEY_ID;
    delete process.env.AWS_SECRET_ACCESS_KEY;

    expect(await resolveAwsCredentials(ORG, { allowServerFallback: true })).toBeNull();
  });

  it('rejects a malformed access key id without storing anything', async () => {
    await expect(storePlatformKey({
      orgId: ORG,
      name: 'bad',
      platform: 'aws',
      values: { accessKeyId: 'nope', secretAccessKey: AWS_PAIR.secretAccessKey },
    })).rejects.toThrow(/Access key ID/);

    expect(await db.select().from(apiTokenSchema)).toHaveLength(0);
  });

  it('exposes the whole document to resolvePlatformCredential', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme AWS', platform: 'aws', values: AWS_PAIR });

    expect(await resolvePlatformCredential(ORG, 'aws')).toEqual(AWS_PAIR);
  });
});

describe('listTokens', () => {
  it('reports the platform and the masked hint, and no secret material', async () => {
    await storePlatformKey({ orgId: ORG, name: 'Acme OpenAI', platform: 'openai', apiKey: OPENAI_KEY });
    const [row] = await listTokens(ORG);

    expect(row).toMatchObject({ name: 'Acme OpenAI', platform: 'openai', keyHint: '…1234' });
    expect(JSON.stringify(row)).not.toContain(OPENAI_KEY);
    expect(Object.keys(row!)).not.toContain('ciphertext');
    expect(Object.keys(row!)).not.toContain('secretHash');
  });

  it('reports a vocion token with no key hint', async () => {
    await issueToken({ orgId: ORG, name: 'app' });
    const [row] = await listTokens(ORG);

    expect(row).toMatchObject({ platform: 'vocion', keyHint: null });
  });
});

describe('the database refuses a half-written credential', () => {
  it('rejects a non-vocion row with no ciphertext', async () => {
    await expect(db.insert(apiTokenSchema).values({
      id: 'broken1',
      orgId: ORG,
      name: 'no ciphertext',
      platform: 'openai',
      secretHash: null,
    })).rejects.toThrow();
  });

  it('rejects a vocion row carrying ciphertext', async () => {
    await expect(db.insert(apiTokenSchema).values({
      id: 'broken2',
      orgId: ORG,
      name: 'mixed shape',
      platform: 'vocion',
      secretHash: 'a'.repeat(64),
      ciphertext: 'ZmFrZQ==',
      nonce: 'ZmFrZQ==',
      authTag: 'ZmFrZQ==',
      dekId: 1,
    })).rejects.toThrow();
  });

  it('rejects a vocion row with no secret hash', async () => {
    await expect(db.insert(apiTokenSchema).values({
      id: 'broken3',
      orgId: ORG,
      name: 'no hash',
      platform: 'vocion',
      secretHash: null,
    })).rejects.toThrow();
  });
});
