import type { Metadata, Viewport } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { ThemeProvider } from 'next-themes';
import { notFound } from 'next/navigation';
import { preload } from 'react-dom';
import { titlePrefix } from '@/libs/envLabel';
import { routing } from '@/libs/I18nRouting';
import { FONT_PRELOADS } from '@/styles/fontPreloads';
import { AppConfig } from '@/utils/AppConfig';
import '@/styles/fonts.css';
import '@/styles/global.css';

// v0.3 — typography stack ported from rev-ai. Outfit drives display headings
// (h1–h4 + `.font-display`), Inter drives body text (default `font-sans`), and
// six heading faces an Org's brand may pick (`libs/branding/fonts.ts`) wait,
// unused, until one is picked — a browser only fetches a face something uses.
//
// SELF-HOSTED, never fetched at build time (2026-10-09). `next/font/google`
// downloaded every face from fonts.googleapis.com during `next build`, and
// that fetch failing broke CI, a release image and a merge to main. The
// files, their @font-face (every subset, with its unicode-range), the
// metric-adjusted fallback faces and the `--font-*` variables are committed
// (`styles/fonts.css`, `public/fonts`, regenerated by
// `scripts/fonts/self-host.mjs`), so the page reads exactly what next/font
// produced and the build reads only the disk. Outfit and Inter's latin files
// are preloaded, as next/font preloaded them.

// Icons are wired via the auto-discovered `app/icon.tsx` +
// `app/apple-icon.tsx` files — they render the Vocion mark
// dynamically at the right sizes. No static icons config needed.
/**
 * Every page title carries the environment, when there is one to carry.
 *
 * `template` applies to any child route that sets a string title; `default`
 * covers the ones that set none. In production `titlePrefix()` is empty and
 * this is the same object it always was.
 */
export const metadata: Metadata = {
  title: {
    template: `${titlePrefix()}%s`,
    default: `${titlePrefix()}${AppConfig.name}`,
  },
  // Added to the Home Screen this opens without browser chrome — and on iOS
  // that is also the only way the app can ever receive a push, so it is the
  // prerequisite for telling somebody their decision is holding work up.
  manifest: '/manifest.webmanifest',
  appleWebApp: { capable: true, statusBarStyle: 'default', title: AppConfig.name },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // An installed app never zooms and never scrolls sideways: content fits the
  // width or scrolls inside its own box (Chris, 2026-09-25: "it should act
  // more like an app"). Pinch and double-tap zoom are off; inputs are 16px so
  // iOS has no reason to zoom them either (ChatComposer).
  maximumScale: 1,
  userScalable: false,
  // The keyboard shrinks the layout instead of covering the composer
  // (Android; iOS already resizes the visual viewport).
  interactiveWidget: 'resizes-content',
  // The installed app draws under the notch and the home indicator rather
  // than letterboxing itself inside them.
  viewportFit: 'cover',
};

export function generateStaticParams() {
  return routing.locales.map(locale => ({ locale }));
}

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  setRequestLocale(locale);
  for (const href of FONT_PRELOADS) {
    preload(href, { as: 'font', type: 'font/woff2', crossOrigin: 'anonymous' });
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider>
            {props.children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
