-- 0110 — the typed briefing document (docs/specs/briefing-v2.md).
--
-- It was 0108 while it was being built. `main` took that number for
-- `action_run.approved_by_agent` (#341) and 0109 for `project.voice_rules`
-- (#370) in the meantime, so this one moved twice rather than reusing either:
-- an applied migration is immutable, and two files sharing a number means one
-- of them never runs somewhere.
--
-- A briefing stops being a markdown blob and becomes a `BriefingV2`: nine
-- named sections, ranked and budgeted in code rather than asked of a model.
-- The markdown stays in `content` — it is what the document renders to, and
-- what every row written before this carries — so nothing needs backfilling
-- and an older publisher keeps working. Nullable jsonb, additive
-- (CONVENTIONS.md rule 2).
ALTER TABLE "briefing" ADD COLUMN IF NOT EXISTS "document" jsonb;
