#!/usr/bin/env node
/**
 * SELF-HOSTED FONTS — run by hand when a face is added or changed, never by
 * the build. `next/font/google` fetched every face from fonts.googleapis.com
 * during `next build`, and that fetch failed often enough to break CI, a
 * release image and a merge to main (2026-10-09). Now the files and the CSS
 * are committed and the build reads them from disk.
 *
 * It asks next's own Google font helpers the same questions `next/font/google`
 * asked — the same Google Fonts URL for the same axes, the same CSS for the
 * same browser, the same fallback metrics — so the output is what the build
 * used to produce: every subset's @font-face with its unicode-range, the
 * metric-adjusted "<Family> Fallback" face, and the `--font-*` variables.
 *
 *   node scripts/fonts/self-host.mjs        (from packages/core)
 *
 * Writes public/fonts/<family>/*.woff2 with the family's OFL.txt beside it,
 * src/styles/fonts.css, and src/styles/fontPreloads.ts. Each face is under the
 * SIL Open Font License 1.1 (public/fonts/README.md).
 */

import { Buffer } from 'node:buffer';
import { execFileSync } from 'node:child_process';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import process from 'node:process';

const require = createRequire(import.meta.url);
const G = 'next/dist/compiled/@next/font/dist/google';
const { getFontAxes } = require(`${G}/get-font-axes`);
const { getGoogleFontsUrl } = require(`${G}/get-google-fonts-url`);
const { fetchCSSFromGoogleFonts } = require(`${G}/fetch-css-from-google-fonts`);
const { getFallbackFontOverrideMetrics } = require(`${G}/get-fallback-font-override-metrics`);
const { validateGoogleFontFunctionCall } = require(`${G}/validate-google-font-function-call`);

const ROOT = process.cwd();
const PUBLIC = path.join(ROOT, 'public', 'fonts');

/**
 * Every face the app loads, exactly as `app/[locale]/layout.tsx` called
 * `next/font/google` before this change. `preload`: its latin file is
 * preloaded (Outfit and Inter, used on every page).
 */
const FACES = [
  { fn: 'Outfit', dir: 'outfit', ofl: 'outfit', opts: { subsets: ['latin'], display: 'swap', variable: '--font-outfit', weight: ['200', '300', '400', '500', '600', '700'] }, preload: true },
  { fn: 'Inter', dir: 'inter', ofl: 'inter', opts: { subsets: ['latin'], display: 'swap', variable: '--font-inter', weight: ['400', '500', '600', '700'] }, preload: true },
  { fn: 'Barlow', dir: 'barlow', ofl: 'barlow', opts: { subsets: ['latin'], display: 'swap', variable: '--font-barlow', weight: ['600', '700', '800'], preload: false } },
  { fn: 'Manrope', dir: 'manrope', ofl: 'manrope', opts: { subsets: ['latin'], display: 'swap', variable: '--font-manrope', preload: false } },
  { fn: 'Space_Grotesk', dir: 'space-grotesk', ofl: 'spacegrotesk', opts: { subsets: ['latin'], display: 'swap', variable: '--font-space-grotesk', preload: false } },
  { fn: 'IBM_Plex_Sans', dir: 'ibm-plex-sans', ofl: 'ibmplexsans', opts: { subsets: ['latin'], display: 'swap', variable: '--font-ibm-plex-sans', weight: ['500', '600', '700'], preload: false } },
  { fn: 'Fraunces', dir: 'fraunces', ofl: 'fraunces', opts: { subsets: ['latin'], display: 'swap', variable: '--font-fraunces', preload: false } },
  { fn: 'Source_Serif_4', dir: 'source-serif-4', ofl: 'sourceserif4', opts: { subsets: ['latin'], display: 'swap', variable: '--font-source-serif-4', preload: false } },
];

async function fetchBuffer(url) {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${url}: HTTP ${res.status}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

const css = [
  '/*',
  ' * GENERATED by scripts/fonts/self-host.mjs — do not edit by hand.',
  ' * Self-hosted faces (SIL Open Font License 1.1, public/fonts/README.md),',
  ' * served from /fonts. No build or page ever fetches a font from Google.',
  ' */',
  '',
];
const variables = [];
const preloads = [];

for (const face of FACES) {
  const call = validateGoogleFontFunctionCall(face.fn, face.opts);
  const axes = getFontAxes(call.fontFamily, call.weights, call.styles, call.selectedVariableAxes);
  const url = getGoogleFontsUrl(call.fontFamily, axes, call.display);
  const sheet = (await fetchCSSFromGoogleFonts(url, call.fontFamily, false)).split('body {', 1)[0];
  const dir = path.join(PUBLIC, face.dir);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });

  // One file per distinct URL, named by its subset (the comment Google puts
  // before each block) and, for a static face, its weight. A variable file
  // Google repeats across weights keeps the subset alone.
  const blocks = sheet.split(/(?=\/\* [\w-]+ \*\/)/);
  const uses = new Map();
  for (const m of sheet.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)) {
    uses.set(m[1], (uses.get(m[1]) ?? 0) + 1);
  }
  const files = new Map();
  let out = '';
  for (const block of blocks) {
    const subset = /\/\* ([\w-]+) \*\//.exec(block)?.[1] ?? 'all';
    const weight = /font-weight: (\d+(?: \d+)?);/.exec(block)?.[1]?.replace(' ', '-');
    let rewritten = block;
    for (const m of block.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)) {
      const remote = m[1];
      if (!files.has(remote)) {
        const name = `${face.dir}-${subset}${uses.get(remote) === 1 && weight ? `-${weight}` : ''}.woff2`;
        writeFileSync(path.join(dir, name), await fetchBuffer(remote));
        files.set(remote, name);
        if (face.preload && subset === 'latin') {
          preloads.push(`/fonts/${face.dir}/${name}`);
        }
      }
      rewritten = rewritten.replace(remote, `/fonts/${face.dir}/${files.get(remote)}`);
    }
    out += rewritten;
  }
  css.push(`/* ${call.fontFamily} */`, out.trim(), '');

  const fallback = getFallbackFontOverrideMetrics(call.fontFamily);
  if (fallback) {
    css.push(
      '@font-face {',
      `  font-family: '${call.fontFamily} Fallback';`,
      `  src: local("${fallback.fallbackFont}");`,
      ...(fallback.ascentOverride ? [`  ascent-override: ${fallback.ascentOverride};`] : []),
      ...(fallback.descentOverride ? [`  descent-override: ${fallback.descentOverride};`] : []),
      ...(fallback.lineGapOverride ? [`  line-gap-override: ${fallback.lineGapOverride};`] : []),
      ...(fallback.sizeAdjust ? [`  size-adjust: ${fallback.sizeAdjust};`] : []),
      '}',
      '',
    );
  }
  variables.push(`  ${face.opts.variable}: '${call.fontFamily}'${fallback ? `, '${call.fontFamily} Fallback'` : ''};`);

  writeFileSync(path.join(dir, 'OFL.txt'), await fetchBuffer(`https://raw.githubusercontent.com/google/fonts/main/ofl/${face.ofl}/OFL.txt`));
  console.log(`${call.fontFamily}: ${files.size} file(s)`);
}

css.push(':root {', ...variables, '}', '');
writeFileSync(path.join(ROOT, 'src', 'styles', 'fonts.css'), css.join('\n'));
writeFileSync(path.join(ROOT, 'src', 'styles', 'fontPreloads.ts'), [
  '// GENERATED by scripts/fonts/self-host.mjs — do not edit by hand.',
  '/** The self-hosted files every page uses, preloaded by the root layout (as `next/font` did). */',
  `export const FONT_PRELOADS: readonly string[] = [${preloads.map(p => `'${p}'`).join(', ')}];`,
  '',
].join('\n'));
console.log(`fonts.css, fontPreloads.ts written; ${preloads.length} preload(s)`);
// The repo's formatter has the last word on the generated files.
execFileSync('npx', ['eslint', '--fix', 'src/styles/fonts.css', 'src/styles/fontPreloads.ts'], { cwd: ROOT, stdio: 'inherit' });
