// GENERATED by scripts/fonts/self-host.mjs — do not edit by hand.
/** The self-hosted files every page uses, preloaded by the root layout (as `next/font` did). */
export const FONT_PRELOADS: readonly string[] = ['/fonts/outfit/outfit-latin.woff2', '/fonts/inter/inter-latin.woff2'];
